baseURL = "https://hugo-daanasma.netlify.app/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "hugo-daanasma"
title = "Daan Asma"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "blog"
name = "Blog"
weight = "2"
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Daan Asma"
description = "This is meta description"
[params.banner]
heading = "Progress towards perfection."
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = ""
[params.call_to_action]
button_label = "Contacteer me"
button_url = "contact"
content = "Een vraag of bezorgdheid? Laat het me weten en ik antwoord je zo snel mogelijk!"
enable = true
title = "Neem contact op"
[params.cookies]
enable = true
expire_days = 2
[params.footer]
address = "Aarschot, Belgium"
content = "<b>email subscription here</b>"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = "Monday–Friday: 9:00AM–5:00PM <br> Saturday & Sunday: 11:00AM–3:00PM"
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
yelp = "#"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
